name: Check Melon Tickets
on:
  schedule:
    - cron: '*/5 * * * *' # 每 5 分钟执行一次
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: mooyoul/melon-ticket-actions@v1.1.0
        with:
          product-id: 210649
          schedule-id: 011117
          seat-id: F1_13
          slack-incoming-webhook-url: https://hooks.slack.com/services/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
          message: '<@U12345678> 快抢票啦！'
